# Generated by Django 4.0.3 on 2022-03-07 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='组织编码'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='level',
            field=models.PositiveIntegerField(help_text='顶级节点为 1', verbose_name='组织层级'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='组织名'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='app.organization', verbose_name='上级组织'),
        ),
    ]
