# Generated by Django 4.0.3 on 2022-03-07 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_organization_code_alter_organization_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='level',
            field=models.PositiveIntegerField(editable=False, help_text='顶级节点为 1', verbose_name='组织层级'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='app.organization', verbose_name='上级组织'),
        ),
    ]
