# Generated by Django 4.0.3 on 2022-03-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_organization_level_alter_organization_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='level',
        ),
    ]
