# Generated by Django 4.0.3 on 2022-03-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_organization_options_remove_organization_seq_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='code',
            new_name='sensor_id',
        ),
        migrations.AlterField(
            model_name='toilet',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='status',
            field=models.CharField(choices=[('NORMAL', '正常'), ('OUT_OF_SERVICE', '停用'), ('MAINTAIN', '维修')], default='NORMAL', max_length=32, verbose_name='当前状态'),
        ),
    ]
