# Generated by Django 4.0.3 on 2022-03-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_code_sensor_sensor_id_alter_toilet_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='built_at',
            field=models.DateField(blank=True, null=True, verbose_name='建造时间'),
        ),
    ]
