# Generated by Django 4.0.3 on 2022-03-22 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_sensor_installation_location_toiletcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=32)),
                ('job_number', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='工号')),
                ('work_card', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='工牌')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], max_length=16, null=True, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
