# Generated by Django 4.0.3 on 2022-03-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='last_communication_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后通信时间'),
        ),
    ]
