# Generated by Django 4.0.3 on 2022-03-29 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_sensor_last_communication_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toiletcomment',
            name='toilet',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='app.toilet'),
        ),
    ]
