# Generated by Django 4.0.3 on 2022-03-31 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_sensor_sensor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='manager',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.staff'),
        ),
    ]
