# Generated by Django 4.0.3 on 2022-03-31 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_toilet_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='toilet',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='app.toilet'),
        ),
    ]
