# Generated by Django 4.0.3 on 2022-04-14 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_sensor_toilet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('agent_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('secret', models.CharField(max_length=255, unique=True)),
                ('authorizer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ticket', models.CharField(max_length=255, unique=True)),
                ('valid', models.BooleanField(default=True, help_text='只能用一次，用过无效', verbose_name='是否有效')),
                ('agent', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='app.agent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
