# Generated by Django 4.0.3 on 2022-04-14 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_agent_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='valid',
        ),
        migrations.AddField(
            model_name='ticket',
            name='expired_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='used',
            field=models.BooleanField(default=True, help_text='只能用一次，用过无效', verbose_name='是否用过'),
        ),
    ]
