# Generated by Django 4.0.3 on 2022-04-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_ticket_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('terminal_id', models.CharField(max_length=64, unique=True, verbose_name='终端号')),
                ('version_code', models.PositiveIntegerField()),
                ('version_name', models.CharField(max_length=64)),
                ('bluetooth_is_online', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
