# Generated by Django 4.0.3 on 2022-04-21 09:21

import app.models.user
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_appversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='toiletcomment',
            name='anonymous',
            field=models.BooleanField(default=False, verbose_name='是否匿名'),
        ),
        migrations.AddField(
            model_name='toiletcomment',
            name='photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='toiletcomment',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WeChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=100, null=True)),
                ('avatar', models.CharField(max_length=255, null=True)),
                ('unionid', models.CharField(max_length=100, null=True)),
                ('gender', models.IntegerField(default=app.models.user.WeChatGenderEnum['UNKNOWN'], verbose_name=app.models.user.WeChatGenderEnum)),
                ('city', models.CharField(max_length=100, null=True)),
                ('province', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('session_key', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
