# Generated by Django 4.0.3 on 2022-04-22 01:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_toiletcomment_anonymous_toiletcomment_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toiletcomment',
            name='photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
