# Generated by Django 4.0.3 on 2022-05-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_toiletcomment_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='camera_channel',
            field=models.CharField(max_length=64, null=True, verbose_name='通道'),
        ),
        migrations.AddField(
            model_name='toilet',
            name='camera_serial',
            field=models.CharField(max_length=64, null=True, verbose_name='摄像机国标编号'),
        ),
    ]
