# Generated by Django 4.0.3 on 2022-06-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_toilet_camera_channel_toilet_camera_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCardScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('work_card', models.CharField(max_length=64, verbose_name='工牌')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
