# Generated by Django 4.0.3 on 2022-06-09 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_workcardscan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('day', models.DateField(verbose_name='考勤日期')),
                ('start_working_time', models.DateTimeField(verbose_name='上班时间')),
                ('clock_in', models.DateTimeField(blank=True, null=True, verbose_name='上班打卡时间')),
                ('quiting_time', models.DateTimeField(verbose_name='下班时间')),
                ('clock_out', models.DateTimeField(blank=True, null=True, verbose_name='下班打卡时间')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
            ],
            options={
                'unique_together': {('day', 'staff_id')},
            },
        ),
    ]
