# Generated by Django 4.0.3 on 2022-06-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start', models.TimeField(verbose_name='上班时间')),
                ('end', models.TimeField(verbose_name='下班时间')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='attendance',
            name='quiting_time',
            field=models.TimeField(verbose_name='下班时间'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='start_working_time',
            field=models.TimeField(verbose_name='上班时间'),
        ),
    ]
