# Generated by Django 4.0.3 on 2022-06-10 03:28

from django.db import migrations


def initial_working_time(apps, schema_editor):
    # We can't import the WorkingTime model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    WorkingTime = apps.get_model('app', 'WorkingTime')
    WorkingTime.objects.create(start="09:00", end="18:00")


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0025_workingtime_alter_attendance_quiting_time_and_more'),
    ]

    operations = [
        migrations.RunPython(initial_working_time)
    ]
