# Generated by Django 4.0.3 on 2022-06-10 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20220610_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='manage_toilet',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.toilet'),
        ),
        migrations.AddField(
            model_name='workcardscan',
            name='toilet',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.toilet'),
        ),
    ]
