# Generated by Django 4.0.5 on 2022-06-27 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='meet_specification',
            new_name='meet_spec',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='street_code',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='street_name',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=32, unique=True, verbose_name='车牌号'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=64, verbose_name='区域名')),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, 'City'), (2, 'Area'), (3, 'Street'), (4, 'Community')], verbose_name='区域级别')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycle.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recycle.region'),
        ),
    ]
