# Generated by Django 4.0.5 on 2022-06-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, verbose_name='公司名称')),
                ('uniform_social_credit_code', models.CharField(max_length=32, verbose_name='统一社会信用代码')),
                ('address', models.CharField(max_length=255, verbose_name='公司地址')),
                ('area_code', models.CharField(max_length=32, verbose_name='注册区编码')),
                ('area_name', models.CharField(max_length=32, verbose_name='注册区名称')),
                ('form', models.CharField(max_length=32, verbose_name='企业类型')),
                ('legal_person', models.CharField(max_length=32, verbose_name='法人')),
                ('legal_person_id_card', models.CharField(max_length=32, verbose_name='法人身份证')),
                ('business_license', models.CharField(max_length=512, verbose_name='营业执照')),
                ('qualification', models.CharField(max_length=512, verbose_name='资质')),
                ('manager_name', models.CharField(max_length=32, verbose_name='姓名')),
                ('manager_id_card', models.CharField(max_length=32, verbose_name='身份证')),
                ('manager_phone', models.CharField(max_length=32, verbose_name='联系电话')),
                ('manager_email', models.EmailField(max_length=254)),
                ('manager_address', models.CharField(max_length=255, verbose_name='居住地址')),
                ('manager_id_card_front', models.CharField(max_length=255, verbose_name='身份证正面')),
                ('manager_id_card_back', models.CharField(max_length=255, verbose_name='身份证背面')),
                ('state', models.CharField(choices=[('APPROVING', '审核中'), ('APPROVED', '审核通过'), ('REJECTED', '审核拒绝')], default='APPROVING', max_length=32, verbose_name='审核状态')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='审核拒绝原因')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
