# Generated by Django 4.0.5 on 2022-06-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0002_rename_meet_specification_vehicle_meet_spec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='rank',
            field=models.SmallIntegerField(default=0, verbose_name='排序'),
        ),
    ]
