# Generated by Django 4.0.5 on 2022-06-27 07:35

from django.db import migrations

from recycle.models import RegionGrade

regions = {
    "110113001000": "胜利街道",
    "110113002000": "光明街道",
    "110113003000": "仁和镇",
    "110113004000": "后沙峪镇",
    "110113005000": "天竺镇",
    "110113006000": "杨镇",
    "110113007000": "牛栏山镇",
    "110113008000": "南法信镇",
    "110113009000": "马坡镇",
    "110113010000": "石园街道",
    "110113011000": "空港街道",
    "110113012000": "双丰街道",
    "110113013000": "旺泉街道",
    "110113101000": "高丽营镇",
    "110113104000": "李桥镇",
    "110113105000": "李遂镇",
    "110113106000": "南彩镇",
    "110113108000": "北务镇",
    "110113109000": "大孙各庄镇",
    "110113110000": "张镇",
    "110113111000": "龙湾屯镇",
    "110113112000": "木林镇",
    "110113113000": "北小营镇",
    "110113115000": "北石槽镇",
    "110113116000": "赵全营镇",
    "110113117000": "临空经济核心区",
}


def initial_regions(apps, schema_editor):
    # We can't import the Region model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Region = apps.get_model('recycle', 'Region')
    shunyi = Region.objects.create(code="110113000000", name="顺义区", grade=RegionGrade.AREA)
    for code, name in regions.items():
        Region.objects.create(code=code, name=name, grade=RegionGrade.STREET, parent=shunyi)


class Migration(migrations.Migration):
    dependencies = [
        ('recycle', '0004_alter_region_parent'),
    ]

    operations = [
        migrations.RunPython(initial_regions)
    ]
