# Generated by Django 4.0.5 on 2022-06-27 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0005_auto_20220627_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='area_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='area_name',
        ),
        migrations.AddField(
            model_name='company',
            name='registration_region',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recycle.region'),
        ),
    ]
