# Generated by Django 4.0.5 on 2022-06-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0009_platformmanager'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driver',
            unique_together={('company', 'phone'), ('company', 'id_card')},
        ),
    ]
