# Generated by Django 4.0.5 on 2022-06-29 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0010_alter_driver_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='中转站名称')),
                ('management_company', models.CharField(max_length=255, verbose_name='管理单位')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('longitude', models.DecimalField(decimal_places=11, max_digits=20, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=11, max_digits=20, verbose_name='维度')),
                ('nature', models.CharField(choices=[('HOLD', '自有'), ('LEASE', '租赁'), ('ENTRUSTMENT', '委托')], max_length=32, verbose_name='场所性质')),
                ('varieties', models.CharField(max_length=255, verbose_name='经营品种')),
                ('manager_name', models.CharField(max_length=32, verbose_name='负责人姓名')),
                ('manager_phone', models.CharField(max_length=32, verbose_name='负责人联系方式')),
                ('community', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_stations', to='recycle.region')),
                ('street', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='street_stations', to='recycle.region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
