# Generated by Django 4.0.5 on 2022-06-29 09:04

import django.contrib.postgres.fields
from django.db import migrations, models
import recycle.models.company


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0011_transferstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyapplication',
            name='form',
            field=models.CharField(choices=[(recycle.models.company.CompanyForm['PERSONAL'], 'PERSONAL'), (recycle.models.company.CompanyForm['PARTNERSHIP'], 'PARTNERSHIP'), (recycle.models.company.CompanyForm['JOINT_STOCK'], 'JOINT-STOCK'), (recycle.models.company.CompanyForm['LIMITED'], 'LIMITED')], max_length=32, verbose_name='企业类型'),
        ),
        migrations.AlterField(
            model_name='transferstation',
            name='varieties',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PAPER', '废纸'), ('METAL', '废金属'), ('PLASTIC', '废塑料'), ('GLASS', '废玻璃'), ('FABRIC', '废织物'), ('ELECTRONICS', '废弃电器电子产品'), ('LARGE_FURNITURE', '废弃大件家具')], max_length=32), blank=True, default=list, size=None, verbose_name='经营品种'),
        ),
    ]
