# Generated by Django 4.0.5 on 2022-06-30 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0012_alter_companyapplication_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('plate_number', models.CharField(max_length=32, verbose_name='车牌号')),
                ('driver', models.CharField(max_length=32, verbose_name='司机姓名')),
                ('weigher', models.CharField(max_length=32, verbose_name='司磅员姓名')),
                ('carrier_name', models.CharField(max_length=255, verbose_name='运输单位')),
                ('tare_weight', models.FloatField(verbose_name='皮重（kg）')),
                ('gross_weight', models.FloatField(verbose_name='毛重（kg）')),
                ('net_weight', models.FloatField(verbose_name='净重（kg）')),
                ('tare_weight_time', models.DateTimeField(verbose_name='皮重时间')),
                ('gross_weight_time', models.DateTimeField(verbose_name='毛重时间')),
                ('net_weight_time', models.DateTimeField(verbose_name='净重时间')),
                ('recyclables_type', models.CharField(max_length=32, verbose_name='可回收物类型')),
                ('category', models.CharField(max_length=32, verbose_name='细分品类')),
                ('plate_number_photo_in', models.CharField(blank=True, max_length=512, null=True, verbose_name='进场车牌识别照片')),
                ('vehicle_head_photo_in', models.CharField(blank=True, max_length=512, null=True, verbose_name='进场车头照片')),
                ('vehicle_roof_photo_in', models.CharField(blank=True, max_length=512, null=True, verbose_name='进场车顶照片')),
                ('plate_number_photo_out', models.CharField(blank=True, max_length=512, null=True, verbose_name='出场车牌识别照片')),
                ('vehicle_head_photo_out', models.CharField(blank=True, max_length=512, null=True, verbose_name='出场车头照片')),
                ('vehicle_roof_photo_out', models.CharField(blank=True, max_length=512, null=True, verbose_name='出场车顶照片')),
                ('place_to_go', models.CharField(max_length=128, verbose_name='去向')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycle.transferstation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InboundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('plate_number', models.CharField(max_length=32, verbose_name='车牌号')),
                ('driver', models.CharField(max_length=32, verbose_name='司机姓名')),
                ('weigher', models.CharField(max_length=32, verbose_name='司磅员姓名')),
                ('carrier_name', models.CharField(max_length=255, verbose_name='运输单位')),
                ('source_street_name', models.CharField(max_length=255, verbose_name='来源街道')),
                ('tare_weight', models.FloatField(verbose_name='皮重（kg）')),
                ('gross_weight', models.FloatField(verbose_name='毛重（kg）')),
                ('net_weight', models.FloatField(verbose_name='净重（kg）')),
                ('tare_weight_time', models.DateTimeField(verbose_name='皮重时间')),
                ('gross_weight_time', models.DateTimeField(verbose_name='毛重时间')),
                ('net_weight_time', models.DateTimeField(verbose_name='净重时间')),
                ('recyclables_type', models.CharField(max_length=32, verbose_name='可回收物类型')),
                ('plate_number_photo_in', models.CharField(blank=True, max_length=512, null=True, verbose_name='进场车牌识别照片')),
                ('vehicle_head_photo_in', models.CharField(blank=True, max_length=512, null=True, verbose_name='进场车头照片')),
                ('vehicle_roof_photo_in', models.CharField(blank=True, max_length=512, null=True, verbose_name='进场车顶照片')),
                ('plate_number_photo_out', models.CharField(blank=True, max_length=512, null=True, verbose_name='出场车牌识别照片')),
                ('vehicle_head_photo_out', models.CharField(blank=True, max_length=512, null=True, verbose_name='出场车头照片')),
                ('vehicle_roof_photo_out', models.CharField(blank=True, max_length=512, null=True, verbose_name='出场车顶照片')),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recycle.company', verbose_name='清运公司')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycle.transferstation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
