# Generated by Django 4.0.5 on 2022-07-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0013_outboundrecord_inboundrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.BigIntegerField(blank=True, null=True, verbose_name='地区编码')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='地区名称')),
                ('lon_lat', models.TextField(blank=True, verbose_name='经纬度')),
                ('lat_center', models.DecimalField(blank=True, decimal_places=11, max_digits=20, null=True)),
                ('lon_center', models.DecimalField(blank=True, decimal_places=11, max_digits=20, null=True)),
                ('is_null', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
