# Generated by Django 4.0.5 on 2022-07-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0016_alter_vehicle_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundrecord',
            name='carrier_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='运输单位'),
        ),
        migrations.AlterField(
            model_name='inboundrecord',
            name='driver',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='司机姓名'),
        ),
        migrations.AlterField(
            model_name='inboundrecord',
            name='source_street_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='来源街道'),
        ),
        migrations.AlterField(
            model_name='inboundrecord',
            name='weigher',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='司磅员姓名'),
        ),
    ]
