# Generated by Django 4.0.5 on 2022-07-01 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0017_alter_inboundrecord_carrier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferstation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
