# Generated by Django 4.0.5 on 2022-07-01 09:50

from django.db import migrations, models
import infra.utils


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0018_transferstation_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferstation',
            name='uuid',
            field=models.UUIDField(default=infra.utils.uuid1),
        ),
    ]
