# Generated by Django 4.0.5 on 2022-07-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0019_alter_transferstation_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundrecord',
            name='carrier_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='运输单位'),
        ),
        migrations.AlterField(
            model_name='outboundrecord',
            name='driver',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='司机姓名'),
        ),
        migrations.AlterField(
            model_name='outboundrecord',
            name='place_to_go',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='去向'),
        ),
        migrations.AlterField(
            model_name='outboundrecord',
            name='weigher',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='司磅员姓名'),
        ),
    ]
