# Generated by Django 4.0.5 on 2022-07-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0020_alter_outboundrecord_carrier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundrecord',
            name='uuid',
            field=models.UUIDField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
