# Generated by Django 4.0.5 on 2022-07-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0021_inboundrecord_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundrecord',
            name='uuid',
            field=models.UUIDField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
