# Generated by Django 4.0.5 on 2022-07-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0022_outboundrecord_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundrecord',
            name='uuid',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='outboundrecord',
            name='uuid',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
