# Generated by Django 4.0.5 on 2022-07-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0023_alter_inboundrecord_uuid_alter_outboundrecord_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('plate_number', models.CharField(max_length=32, null=True, verbose_name='车牌号')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('altitude', models.FloatField(verbose_name='海拔(米)')),
                ('speed', models.FloatField(verbose_name='速度')),
                ('direction', models.IntegerField(verbose_name='方向')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
