# Generated by Django 4.0.5 on 2022-07-05 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0024_latesttrack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboundrecord',
            name='carrier_name',
        ),
        migrations.RemoveField(
            model_name='inboundrecord',
            name='source_street_name',
        ),
        migrations.AddField(
            model_name='inboundrecord',
            name='source_street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='recycle.region'),
        ),
    ]
