# Generated by Django 4.0.6 on 2022-07-13 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0025_remove_inboundrecord_carrier_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymanager',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='VehicleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(choices=[('RECYCLE', '可回收物运输车'), ('LARGE_RUBBISH', '大件垃圾运输车')], max_length=32, verbose_name='车辆类型')),
                ('energy_type', models.CharField(choices=[('OIL', '燃油'), ('NEW_ENERGY', '新能源')], max_length=32, verbose_name='能源类型')),
                ('load', models.FloatField(verbose_name='载重（t）')),
                ('meet_spec', models.BooleanField(verbose_name='是否按规范喷涂')),
                ('plate_number', models.CharField(max_length=32, unique=True, verbose_name='车牌号')),
                ('change_type', models.CharField(choices=[('NEW', '新增'), ('CHANGE', '变更')], max_length=16, verbose_name='变更类型')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycle.company')),
                ('service_street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recycle.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(choices=[('RECYCLE', '可回收物运输车'), ('LARGE_RUBBISH', '大件垃圾运输车')], max_length=32, verbose_name='车辆类型')),
                ('energy_type', models.CharField(choices=[('OIL', '燃油'), ('NEW_ENERGY', '新能源')], max_length=32, verbose_name='能源类型')),
                ('load', models.FloatField(verbose_name='载重（t）')),
                ('meet_spec', models.BooleanField(verbose_name='是否按规范喷涂')),
                ('plate_number', models.CharField(max_length=32, verbose_name='车牌号')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycle.company')),
                ('service_street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recycle.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(choices=[('RECYCLE', '可回收物运输车'), ('LARGE_RUBBISH', '大件垃圾运输车')], max_length=32, verbose_name='车辆类型')),
                ('energy_type', models.CharField(choices=[('OIL', '燃油'), ('NEW_ENERGY', '新能源')], max_length=32, verbose_name='能源类型')),
                ('load', models.FloatField(verbose_name='载重（t）')),
                ('meet_spec', models.BooleanField(verbose_name='是否按规范喷涂')),
                ('plate_number', models.CharField(max_length=32, verbose_name='车牌号')),
                ('change_type', models.CharField(choices=[('NEW', '新增'), ('CHANGE', '变更')], max_length=16, verbose_name='变更类型')),
                ('state', models.CharField(choices=[('APPROVING', '审核中'), ('APPROVED', '审核通过'), ('REJECTED', '审核拒绝')], default='APPROVING', max_length=32, verbose_name='审核状态')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='审核拒绝原因')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycle.company')),
                ('service_street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recycle.region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
