# Generated by Django 4.0.6 on 2022-07-14 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0026_alter_companymanager_email_vehiclehistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformmanager',
            name='region',
            field=models.ForeignKey(db_column='region_code', db_constraint=False, default='110113000000', on_delete=django.db.models.deletion.DO_NOTHING, to='recycle.region', to_field='code'),
        ),
        migrations.AddField(
            model_name='platformmanager',
            name='role',
            field=models.CharField(choices=[('AREA', '区级管理员'), ('STREET', '街道管理员')], default='AREA', max_length=16, verbose_name='角色'),
        ),
    ]
