# Generated by Django 4.0.6 on 2022-07-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0029_alter_vehiclehistory_plate_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='working_years',
        ),
        migrations.AddField(
            model_name='driver',
            name='id_card_back',
            field=models.TextField(null=True, verbose_name='身份证反面'),
        ),
        migrations.AddField(
            model_name='driver',
            name='id_card_front',
            field=models.TextField(null=True, verbose_name='身份证正面'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_photo',
            field=models.TextField(verbose_name='驾驶证照片'),
        ),
    ]
