# Generated by Django 4.0.6 on 2022-08-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0032_vehicle_vehicle_licence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('plate_number', models.CharField(max_length=32, verbose_name='车牌号')),
                ('started_at', models.DateTimeField(verbose_name='事件开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='事件结束时间')),
                ('type', models.CharField(choices=[('OVERLOAD', '超载'), ('SPEEDING', '超速'), ('OVERTIME', '超时')], max_length=16, verbose_name='事件类型')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
