# Generated by Django 4.0.6 on 2022-11-08 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0033_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-started_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='inboundrecord',
            options={'ordering': ['-net_weight_time']},
        ),
        migrations.AlterModelOptions(
            name='outboundrecord',
            options={'ordering': ['-net_weight_time']},
        ),
        migrations.AddField(
            model_name='transferstation',
            name='managed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='recycle.company'),
        ),
    ]
