# Generated by Django 4.0.6 on 2022-12-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0035_servicestreetmodification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inboundrecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='outboundrecord',
            options={},
        ),
        migrations.AlterField(
            model_name='vehicleapplication',
            name='change_type',
            field=models.CharField(choices=[('NEW', '新增'), ('CHANGE', '变更'), ('DELETE', '删除')], max_length=16, verbose_name='变更类型'),
        ),
        migrations.AlterField(
            model_name='vehiclehistory',
            name='change_type',
            field=models.CharField(choices=[('NEW', '新增'), ('CHANGE', '变更'), ('DELETE', '删除')], max_length=16, verbose_name='变更类型'),
        ),
    ]
