# Generated by Django 4.0.6 on 2022-12-08 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0036_alter_inboundrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighValueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('report_date', models.DateField(verbose_name='填报日期')),
                ('high_value_weight', models.FloatField(verbose_name='高值重量（单位吨）')),
                ('low_value_weight', models.FloatField(verbose_name='低值重量（单位吨）')),
                ('reporter', models.CharField(max_length=64, verbose_name='填报人')),
                ('approver', models.CharField(max_length=64, verbose_name='审核人')),
                ('street', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='recycle.region')),
            ],
            options={
                'unique_together': {('street', 'report_date')},
            },
        ),
    ]
